# -*- coding: utf-8 -*-
"""1_normalizacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11cBoCWFQUVY_dLXWlt8hkMb64F4j52rV

# Normalizacion

BLOQUE 1: INSTALACIONES
"""

import pandas as pd
print("✅ pandas:", pd.__version__)

"""BLOQUE 2: CARGAR DATASET ORIGINAL"""

from google.colab import files

uploaded = files.upload()

df = pd.read_csv('sales_data_sample.csv', encoding='latin1')
print(f"✅ Dataset cargado: {df.shape[0]} filas | {df.shape[1]} columnas")
df.head(3)

"""Bloque 3 — Ver tipos de datos y nulos"""

print("=== TIPOS DE DATOS ===")
print(df.dtypes)

print("\n=== VALORES NULOS POR COLUMNA ===")
print(df.isnull().sum())

"""BLOQUE 4: LIMPIEZA DE NULOS"""

# Eliminar columna casi vacía (2521 nulos de 2823)
df.drop(columns=['ADDRESSLINE2'], inplace=True)

# Rellenar nulos de texto con 'UNKNOWN'
cols_texto = ['STATE', 'TERRITORY', 'POSTALCODE']
df[cols_texto] = df[cols_texto].fillna('UNKNOWN')

print("✅ Nulos tratados")
print(f"Nulos restantes: {df.isnull().sum().sum()}")

"""BLOQUE 5: NORMALIZAR TIPOS DE DATOS"""

# Convertir ORDERDATE a fecha
df['ORDERDATE'] = pd.to_datetime(df['ORDERDATE'])

# Asegurar columnas numéricas correctas
df['SALES'] = df['SALES'].astype(float)
df['QUANTITYORDERED'] = df['QUANTITYORDERED'].astype(int)
df['PRICEEACH'] = df['PRICEEACH'].astype(float)

print("✅ Tipos de datos normalizados")
print(df.dtypes)

"""Bloque 6 — Normalizar texto"""

# Columnas de texto a mayúsculas uniformes y sin espacios
cols_upper = ['STATUS', 'PRODUCTLINE', 'CUSTOMERNAME',
              'COUNTRY', 'DEALSIZE', 'TERRITORY']

for col in cols_upper:
    df[col] = df[col].str.strip().str.upper()

print("✅ Texto normalizado")
df.head(3)

"""Bloque 7 — Guardar y descargar dataset normalizado"""

df.to_csv('ventas_normalizado.csv', index=False)
print("✅ Dataset guardado como ventas_normalizado.csv")
print(f"📊 Filas: {df.shape[0]} | Columnas: {df.shape[1]}")

# Descargar a tu PC
from google.colab import files
files.download('ventas_normalizado.csv')