# -*- coding: utf-8 -*-
"""bot_agente.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fJIWagTnW49LUuco0P3f86mvYRDshHpt

# BOT de Ventas — Agente Pandas + RAG + Mistral
Corpus: ventas_normalizado.csv | Embeddings: HuggingFace | VectorDB: ChromaDB | LLM: Mistral
"""

# BLOQUE 1 — Instalacion de dependencias
!pip install -q langchain langchain-community langchain-mistralai langchain-experimental
!pip install -q chromadb sentence-transformers
!pip install -q pandas tabulate langchain-core

print("Todas las dependencias instaladas")

# BLOQUE 2 — Imports
import os
import pandas as pd
from google.colab import files, userdata

from langchain_mistralai import ChatMistralAI
from langchain_community.document_loaders import DataFrameLoader
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma
from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
from langchain_experimental.agents import create_pandas_dataframe_agent

print("Imports correctos")

# BLOQUE 3 — API Key y carga del dataset
import os
from google.colab import files, userdata

os.environ["MISTRAL_API_KEY"] = userdata.get('bot-ventas-rag')
key = os.environ["MISTRAL_API_KEY"]
print(f"API Key cargada: {key[:8]}...")

print("Subi tu archivo ventas_normalizado.csv:")
uploaded = files.upload()
nombre_csv = list(uploaded.keys())[0]
df = pd.read_csv(nombre_csv, encoding='latin-1')

print(f"Dataset cargado: {df.shape[0]} filas x {df.shape[1]} columnas")
df.head(3)

# BLOQUE 4 — Inicializar el LLM Mistral
llm = ChatMistralAI(
    model="mistral-small-latest",
    temperature=0.2,
    api_key=os.environ["MISTRAL_API_KEY"]
)

test = llm.invoke("Responde en una linea: estas listo para analizar datos?")
print("Test de conexion con Mistral:")
print(test.content)

# BLOQUE 5 — Creacion del Agente Pandas
# El agente genera y ejecuta codigo Python sobre el DataFrame
# para responder preguntas numericas y estadisticas

prefix_prompt = """
Eres un asistente experto en analisis de datos de ventas.
Tenes acceso a un DataFrame de pandas llamado df con todas las columnas del dataset.

Instrucciones criticas:
1. Para cualquier pregunta numerica o estadistica, DEBES generar y ejecutar codigo Python.
2. Si te preguntan por ventas totales, usa la columna sales.
3. Si hay valores nulos o unknown, ignoralos en calculos matematicos.
4. Responde siempre en espanol de forma clara y concisa.
"""

agent = create_pandas_dataframe_agent(
    llm,
    df,
    prefix=prefix_prompt,
    verbose=True,
    allow_dangerous_code=True,
    agent_type="tool-calling"
)

print("Agente Pandas creado correctamente")
print(f"Herramientas: {[t.name for t in agent.tools]}")

# BLOQUE 6 — Convertir todas las columnas del CSV a documentos de texto
# fila_a_texto() toma TODAS las columnas automaticamente sin hardcodear nada

def fila_a_texto(row):
    partes = []
    for col in row.index:
        valor = row[col]
        if pd.notna(valor):
            partes.append(f"{col}: {valor}")
    return ". ".join(partes) + "."

df['resumen_fila'] = df.apply(fila_a_texto, axis=1)

print("Ejemplo de fila convertida a texto:")
print(df['resumen_fila'].iloc[0])

loader = DataFrameLoader(df, page_content_column='resumen_fila')
documentos = loader.load()
print(f"\nTotal de documentos indexados: {len(documentos)}")

# BLOQUE 7 — Embeddings con HuggingFace + Base vectorial ChromaDB
# HuggingFace es gratuito y corre local en Colab, no necesita API key
# ChromaDB guarda los vectores en RAM para busqueda por similitud

print("Transformando el corpus a vectores semanticos...")
embeddings_local = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

vector_db = Chroma.from_documents(documentos, embeddings_local)
retriever = vector_db.as_retriever(search_kwargs={"k": 5})

print("Sistema RAG indexado y listo!")

# BLOQUE 8 — Construir la cadena RAG con LCEL
# Flujo: Pregunta -> RAG (ChromaDB) -> Prompt con contexto -> Mistral -> Respuesta

prompt_template = PromptTemplate.from_template("""Eres un analista experto en ventas. Tenes acceso a un corpus
de datos de ventas reales. Responde UNICAMENTE basandote en el contexto
proporcionado. Si la informacion no esta en el contexto, di exactamente:
"No encontre esa informacion en los datos disponibles."

Responde siempre en espanol, de forma clara y concisa.

Contexto del corpus de ventas:
{context}

Pregunta del usuario:
{question}

Respuesta del analista:""")

def formatear_docs(docs):
    return "\n\n".join(doc.page_content for doc in docs)

cadena_rag = (
    {
        "context": retriever | formatear_docs,
        "question": RunnablePassthrough()
    }
    | prompt_template
    | llm
    | StrOutputParser()
)

print("Cadena RAG construida correctamente.")
print("Flujo: Pregunta -> RAG (corpus) -> Mistral -> Respuesta")

# BLOQUE 9 — Funcion preguntar combinada (Agente + RAG)
# El RAG aporta contexto semantico, el agente ejecuta calculos exactos

def preguntar(pregunta: str) -> str:
    print(f"\n{'='*55}")
    print(f"Pregunta: {pregunta}")
    print(f"{'='*55}\n")

    # 1. Recuperar contexto relevante del RAG
    docs = retriever.invoke(pregunta)
    contexto = formatear_docs(docs)

    # 2. Armar pregunta enriquecida con contexto para el agente
    pregunta_con_contexto = f"""
Contexto relevante del dataset:
{contexto}

Pregunta: {pregunta}
"""

    # 3. El agente ejecuta codigo sobre el DataFrame y responde
    resultado = agent.invoke({"input": pregunta_con_contexto})
    respuesta = resultado["output"]

    print(f"\n{'─'*55}")
    print(f"Respuesta:\n{respuesta}")
    print(f"{'─'*55}\n")

    return respuesta

print("Funcion preguntar() lista — Agente + RAG combinados")

# BLOQUE 10 — Pruebas de funcionamiento
preguntar("cuantas filas tiene el dataset?")

preguntar("cual es la linea de producto mas vendida?")

preguntar("cuales son los 5 paises con mas ventas?")

# BLOQUE 11 — Chat interactivo
print("=" * 55)
print("  BOT ANALISTA DE VENTAS — Agente Pandas + RAG + Mistral")
print("  Escribi 'salir' para terminar la sesion.")
print("=" * 55)

while True:
    pregunta = input("\nQue queres saber sobre las ventas?\n> ").strip()

    if not pregunta:
        continue

    if pregunta.lower() == "salir":
        print("\nSesion finalizada. Hasta la proxima!")
        break

    try:
        preguntar(pregunta)
    except Exception as e:
        print(f"\nError: {e}")
        print("Verifica que la API key de Mistral sea valida y que el RAG este inicializado.")