{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyORS3I2mptsKpbkPBgGYG0e"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "source": [
        "# Sistema Multi-Agente — Dataset Titanic"
      ],
      "metadata": {
        "id": "VYJPgenIwifI"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "1. INSTALACIÓN DE DEPENDENCIAS"
      ],
      "metadata": {
        "id": "EoWM8sh9wsri"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install -q transformers torch scikit-learn pandas numpy matplotlib seaborn"
      ],
      "metadata": {
        "id": "0Cqnpt8vwLYK"
      },
      "execution_count": 8,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "2. Imports y configuración global"
      ],
      "metadata": {
        "id": "ta4nKT-fw1eZ"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "import pandas as pd\n",
        "import numpy as np\n",
        "import warnings\n",
        "import matplotlib.pyplot as plt\n",
        "import seaborn as sns\n",
        "from datetime import datetime\n",
        "\n",
        "# Scikit-learn\n",
        "from sklearn.model_selection import StratifiedKFold, cross_val_score\n",
        "from sklearn.preprocessing import StandardScaler, LabelEncoder\n",
        "from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier\n",
        "from sklearn.linear_model import LogisticRegression\n",
        "from sklearn.metrics import (\n",
        "    accuracy_score, classification_report,\n",
        "    confusion_matrix, roc_auc_score\n",
        ")\n",
        "from sklearn.impute import SimpleImputer\n",
        "\n",
        "# Transformers (HuggingFace)\n",
        "import torch\n",
        "from transformers import AutoTokenizer, AutoModel\n",
        "\n",
        "warnings.filterwarnings('ignore')\n",
        "print(\"Imports listos\")\n",
        "print(f\"PyTorch: {torch.__version__}\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "0GVzsUjnw71T",
        "outputId": "d4dc4c27-4452-41a5-9163-3ec6ee2b25c8"
      },
      "execution_count": 10,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Imports listos\n",
            "PyTorch: 2.11.0+cpu\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "3. Carga del Dataset"
      ],
      "metadata": {
        "id": "mQqO-sLbxHlU"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "from google.colab import files\n",
        "uploaded = files.upload()\n",
        "df_raw = pd.read_csv(list(uploaded.keys())[0])"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 74
        },
        "id": "0aDmqifIxJkS",
        "outputId": "07365431-34bc-45c5-cfcd-d3a2682cbce2"
      },
      "execution_count": 11,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ],
            "text/html": [
              "\n",
              "     <input type=\"file\" id=\"files-082a7be1-7839-4bd0-b1f6-8bdb84e3043f\" name=\"files[]\" multiple disabled\n",
              "        style=\"border:none\" />\n",
              "     <output id=\"result-082a7be1-7839-4bd0-b1f6-8bdb84e3043f\">\n",
              "      Upload widget is only available when the cell has been executed in the\n",
              "      current browser session. Please rerun this cell to enable.\n",
              "      </output>\n",
              "      <script>// Copyright 2017 Google LLC\n",
              "//\n",
              "// Licensed under the Apache License, Version 2.0 (the \"License\");\n",
              "// you may not use this file except in compliance with the License.\n",
              "// You may obtain a copy of the License at\n",
              "//\n",
              "//      http://www.apache.org/licenses/LICENSE-2.0\n",
              "//\n",
              "// Unless required by applicable law or agreed to in writing, software\n",
              "// distributed under the License is distributed on an \"AS IS\" BASIS,\n",
              "// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n",
              "// See the License for the specific language governing permissions and\n",
              "// limitations under the License.\n",
              "\n",
              "/**\n",
              " * @fileoverview Helpers for google.colab Python module.\n",
              " */\n",
              "(function(scope) {\n",
              "function span(text, styleAttributes = {}) {\n",
              "  const element = document.createElement('span');\n",
              "  element.textContent = text;\n",
              "  for (const key of Object.keys(styleAttributes)) {\n",
              "    element.style[key] = styleAttributes[key];\n",
              "  }\n",
              "  return element;\n",
              "}\n",
              "\n",
              "// Max number of bytes which will be uploaded at a time.\n",
              "const MAX_PAYLOAD_SIZE = 100 * 1024;\n",
              "\n",
              "function _uploadFiles(inputId, outputId) {\n",
              "  const steps = uploadFilesStep(inputId, outputId);\n",
              "  const outputElement = document.getElementById(outputId);\n",
              "  // Cache steps on the outputElement to make it available for the next call\n",
              "  // to uploadFilesContinue from Python.\n",
              "  outputElement.steps = steps;\n",
              "\n",
              "  return _uploadFilesContinue(outputId);\n",
              "}\n",
              "\n",
              "// This is roughly an async generator (not supported in the browser yet),\n",
              "// where there are multiple asynchronous steps and the Python side is going\n",
              "// to poll for completion of each step.\n",
              "// This uses a Promise to block the python side on completion of each step,\n",
              "// then passes the result of the previous step as the input to the next step.\n",
              "function _uploadFilesContinue(outputId) {\n",
              "  const outputElement = document.getElementById(outputId);\n",
              "  const steps = outputElement.steps;\n",
              "\n",
              "  const next = steps.next(outputElement.lastPromiseValue);\n",
              "  return Promise.resolve(next.value.promise).then((value) => {\n",
              "    // Cache the last promise value to make it available to the next\n",
              "    // step of the generator.\n",
              "    outputElement.lastPromiseValue = value;\n",
              "    return next.value.response;\n",
              "  });\n",
              "}\n",
              "\n",
              "/**\n",
              " * Generator function which is called between each async step of the upload\n",
              " * process.\n",
              " * @param {string} inputId Element ID of the input file picker element.\n",
              " * @param {string} outputId Element ID of the output display.\n",
              " * @return {!Iterable<!Object>} Iterable of next steps.\n",
              " */\n",
              "function* uploadFilesStep(inputId, outputId) {\n",
              "  const inputElement = document.getElementById(inputId);\n",
              "  inputElement.disabled = false;\n",
              "\n",
              "  const outputElement = document.getElementById(outputId);\n",
              "  outputElement.innerHTML = '';\n",
              "\n",
              "  const pickedPromise = new Promise((resolve) => {\n",
              "    inputElement.addEventListener('change', (e) => {\n",
              "      resolve(e.target.files);\n",
              "    });\n",
              "  });\n",
              "\n",
              "  const cancel = document.createElement('button');\n",
              "  inputElement.parentElement.appendChild(cancel);\n",
              "  cancel.textContent = 'Cancel upload';\n",
              "  const cancelPromise = new Promise((resolve) => {\n",
              "    cancel.onclick = () => {\n",
              "      resolve(null);\n",
              "    };\n",
              "  });\n",
              "\n",
              "  // Wait for the user to pick the files.\n",
              "  const files = yield {\n",
              "    promise: Promise.race([pickedPromise, cancelPromise]),\n",
              "    response: {\n",
              "      action: 'starting',\n",
              "    }\n",
              "  };\n",
              "\n",
              "  cancel.remove();\n",
              "\n",
              "  // Disable the input element since further picks are not allowed.\n",
              "  inputElement.disabled = true;\n",
              "\n",
              "  if (!files) {\n",
              "    return {\n",
              "      response: {\n",
              "        action: 'complete',\n",
              "      }\n",
              "    };\n",
              "  }\n",
              "\n",
              "  for (const file of files) {\n",
              "    const li = document.createElement('li');\n",
              "    li.append(span(file.name, {fontWeight: 'bold'}));\n",
              "    li.append(span(\n",
              "        `(${file.type || 'n/a'}) - ${file.size} bytes, ` +\n",
              "        `last modified: ${\n",
              "            file.lastModifiedDate ? file.lastModifiedDate.toLocaleDateString() :\n",
              "                                    'n/a'} - `));\n",
              "    const percent = span('0% done');\n",
              "    li.appendChild(percent);\n",
              "\n",
              "    outputElement.appendChild(li);\n",
              "\n",
              "    const fileDataPromise = new Promise((resolve) => {\n",
              "      const reader = new FileReader();\n",
              "      reader.onload = (e) => {\n",
              "        resolve(e.target.result);\n",
              "      };\n",
              "      reader.readAsArrayBuffer(file);\n",
              "    });\n",
              "    // Wait for the data to be ready.\n",
              "    let fileData = yield {\n",
              "      promise: fileDataPromise,\n",
              "      response: {\n",
              "        action: 'continue',\n",
              "      }\n",
              "    };\n",
              "\n",
              "    // Use a chunked sending to avoid message size limits. See b/62115660.\n",
              "    let position = 0;\n",
              "    do {\n",
              "      const length = Math.min(fileData.byteLength - position, MAX_PAYLOAD_SIZE);\n",
              "      const chunk = new Uint8Array(fileData, position, length);\n",
              "      position += length;\n",
              "\n",
              "      const base64 = btoa(String.fromCharCode.apply(null, chunk));\n",
              "      yield {\n",
              "        response: {\n",
              "          action: 'append',\n",
              "          file: file.name,\n",
              "          data: base64,\n",
              "        },\n",
              "      };\n",
              "\n",
              "      let percentDone = fileData.byteLength === 0 ?\n",
              "          100 :\n",
              "          Math.round((position / fileData.byteLength) * 100);\n",
              "      percent.textContent = `${percentDone}% done`;\n",
              "\n",
              "    } while (position < fileData.byteLength);\n",
              "  }\n",
              "\n",
              "  // All done.\n",
              "  yield {\n",
              "    response: {\n",
              "      action: 'complete',\n",
              "    }\n",
              "  };\n",
              "}\n",
              "\n",
              "scope.google = scope.google || {};\n",
              "scope.google.colab = scope.google.colab || {};\n",
              "scope.google.colab._files = {\n",
              "  _uploadFiles,\n",
              "  _uploadFilesContinue,\n",
              "};\n",
              "})(self);\n",
              "</script> "
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Saving titanic.csv to titanic.csv\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "AGENTE 1 — Normalizador"
      ],
      "metadata": {
        "id": "R5mmzmFByJWa"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "class AgenteNormalizador:\n",
        "    \"\"\"\n",
        "    AGENTE 1 — Normalizador\n",
        "    Recibe el DataFrame crudo y retorna uno limpio, listo para el Entrenador.\n",
        "    \"\"\"\n",
        "\n",
        "    def __init__(self):\n",
        "        self.scaler = StandardScaler()\n",
        "        self.imputer_num = SimpleImputer(strategy='median')\n",
        "        self.log = []          # registro de acciones\n",
        "\n",
        "    def _registrar(self, msg):\n",
        "        self.log.append(msg)\n",
        "        print(f\"  [Agente 1] {msg}\")\n",
        "\n",
        "    # ── helpers ──────────────────────────────────────────────\n",
        "\n",
        "    def _limpiar(self, df):\n",
        "        \"\"\"Elimina columnas de alta cardinalidad / baja utilidad.\"\"\"\n",
        "        antes = df.shape[1]\n",
        "        df = df.drop(columns=['PassengerId', 'Ticket', 'Cabin'], errors='ignore')\n",
        "        self._registrar(f\"Columnas eliminadas: PassengerId, Ticket, Cabin ({antes} → {df.shape[1]} cols)\")\n",
        "        return df\n",
        "\n",
        "    def _extraer_titulo(self, df):\n",
        "        \"\"\"Extrae el título del nombre (Mr., Mrs., Miss., etc.).\"\"\"\n",
        "        df = df.copy()\n",
        "        df['Title'] = df['Name'].str.extract(r' ([A-Za-z]+)\\.')\n",
        "        rare = df['Title'].value_counts()\n",
        "        rare_titles = rare[rare < 10].index\n",
        "        df['Title'] = df['Title'].replace(rare_titles, 'Rare')\n",
        "        self._registrar(f\"Títulos extraídos del nombre: {df['Title'].unique().tolist()}\")\n",
        "        return df\n",
        "\n",
        "    def _imputar(self, df):\n",
        "        \"\"\"Imputa valores faltantes.\"\"\"\n",
        "        faltantes_antes = df.isnull().sum().sum()\n",
        "\n",
        "        # Edad → mediana por título\n",
        "        df['Age'] = df.groupby('Title')['Age'].transform(\n",
        "            lambda x: x.fillna(x.median())\n",
        "        )\n",
        "        # Embarked → moda\n",
        "        df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])\n",
        "        # Fare → mediana\n",
        "        df['Fare'] = df['Fare'].fillna(df['Fare'].median())\n",
        "\n",
        "        faltantes_despues = df.isnull().sum().sum()\n",
        "        self._registrar(\n",
        "            f\"Imputación: {faltantes_antes} valores nulos → {faltantes_despues}\"\n",
        "        )\n",
        "        return df\n",
        "\n",
        "    def _feature_engineering(self, df):\n",
        "        \"\"\"Crea features derivadas.\"\"\"\n",
        "        df = df.copy()\n",
        "        df['FamilySize'] = df['SibSp'] + df['Parch'] + 1\n",
        "        df['IsAlone']    = (df['FamilySize'] == 1).astype(int)\n",
        "        df['FareBand']   = pd.qcut(df['Fare'], 4, labels=False, duplicates='drop')\n",
        "        df['AgeBand']    = pd.cut(df['Age'], bins=[0,12,18,35,60,100],\n",
        "                                  labels=[0,1,2,3,4])\n",
        "        self._registrar(\"Features creadas: FamilySize, IsAlone, FareBand, AgeBand\")\n",
        "        return df\n",
        "\n",
        "    def _codificar(self, df):\n",
        "        \"\"\"Codifica variables categóricas con LabelEncoder.\"\"\"\n",
        "        cats = ['Sex', 'Embarked', 'Title']\n",
        "        for col in cats:\n",
        "            le = LabelEncoder()\n",
        "            df[col] = le.fit_transform(df[col].astype(str))\n",
        "        self._registrar(f\"Columnas codificadas: {cats}\")\n",
        "        return df\n",
        "\n",
        "    def _escalar(self, df, cols_num):\n",
        "        \"\"\"Escala columnas numéricas.\"\"\"\n",
        "        df[cols_num] = self.scaler.fit_transform(df[cols_num])\n",
        "        self._registrar(f\"Escalado StandardScaler aplicado a: {cols_num}\")\n",
        "        return df\n",
        "\n",
        "    # ── pipeline principal ────────────────────────────────────\n",
        "\n",
        "    def procesar(self, df_raw):\n",
        "        print(\"\\n\" + \"=\"*60)\n",
        "        print(\"AGENTE 1 — NORMALIZADOR\")\n",
        "        print(\"=\"*60)\n",
        "\n",
        "        df = df_raw.copy()\n",
        "        df = self._limpiar(df)\n",
        "        df = self._extraer_titulo(df)\n",
        "        df = self._imputar(df)\n",
        "        df = self._feature_engineering(df)\n",
        "        df = self._codificar(df)\n",
        "\n",
        "        # Columnas a escalar\n",
        "        cols_numericas = ['Age', 'Fare', 'FamilySize']\n",
        "        df = self._escalar(df, cols_numericas)\n",
        "\n",
        "        # Conservar columna Name para el Agente 2 (Transformer)\n",
        "        nombres = df_raw['Name'].reset_index(drop=True)\n",
        "\n",
        "        # Features finales (sin Name)\n",
        "        feature_cols = [\n",
        "            'Pclass','Sex','Age','SibSp','Parch','Fare',\n",
        "            'Embarked','Title','FamilySize','IsAlone','FareBand','AgeBand'\n",
        "        ]\n",
        "        df_clean = df[feature_cols + ['Survived']].copy()\n",
        "        df_clean['AgeBand'] = df_clean['AgeBand'].astype(float)\n",
        "\n",
        "        self._registrar(f\"Dataset limpio: {df_clean.shape[0]} filas × {df_clean.shape[1]} cols\")\n",
        "        print(\"\\nAgente 1 finalizado.\")\n",
        "\n",
        "        return df_clean, nombres\n",
        "\n",
        "\n",
        "# Ejecutar Agente 1\n",
        "agente1 = AgenteNormalizador()\n",
        "df_clean, nombres = agente1.procesar(df_raw)\n",
        "\n",
        "print(\"\\nDataset limpio (primeras filas):\")\n",
        "df_clean.head()"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 494
        },
        "id": "FyTvxCZKyZag",
        "outputId": "cae68ddb-c113-416d-ab47-04536ed9dd9a"
      },
      "execution_count": 12,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\n",
            "============================================================\n",
            "AGENTE 1 — NORMALIZADOR\n",
            "============================================================\n",
            "  [Agente 1] Columnas eliminadas: PassengerId, Ticket, Cabin (12 → 9 cols)\n",
            "  [Agente 1] Títulos extraídos del nombre: ['Mr', 'Mrs', 'Miss', 'Master', 'Rare']\n",
            "  [Agente 1] Imputación: 179 valores nulos → 0\n",
            "  [Agente 1] Features creadas: FamilySize, IsAlone, FareBand, AgeBand\n",
            "  [Agente 1] Columnas codificadas: ['Sex', 'Embarked', 'Title']\n",
            "  [Agente 1] Escalado StandardScaler aplicado a: ['Age', 'Fare', 'FamilySize']\n",
            "  [Agente 1] Dataset limpio: 891 filas × 13 cols\n",
            "\n",
            "Agente 1 finalizado.\n",
            "\n",
            "Dataset limpio (primeras filas):\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "   Pclass  Sex       Age  SibSp  Parch      Fare  Embarked  Title  FamilySize  \\\n",
              "0       3    1 -0.557365      1      0 -0.502445         2      2    0.059160   \n",
              "1       1    0  0.649713      1      0  0.786845         0      3    0.059160   \n",
              "2       3    0 -0.255596      0      0 -0.488854         2      1   -0.560975   \n",
              "3       1    0  0.423386      1      0  0.420730         2      3    0.059160   \n",
              "4       3    1  0.423386      0      0 -0.486337         2      2   -0.560975   \n",
              "\n",
              "   IsAlone  FareBand  AgeBand  Survived  \n",
              "0        0         0      2.0         0  \n",
              "1        0         3      3.0         1  \n",
              "2        1         1      2.0         1  \n",
              "3        0         3      2.0         1  \n",
              "4        1         1      2.0         0  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-f0a77a0c-65d4-44d3-960f-693431d3187f\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>Pclass</th>\n",
              "      <th>Sex</th>\n",
              "      <th>Age</th>\n",
              "      <th>SibSp</th>\n",
              "      <th>Parch</th>\n",
              "      <th>Fare</th>\n",
              "      <th>Embarked</th>\n",
              "      <th>Title</th>\n",
              "      <th>FamilySize</th>\n",
              "      <th>IsAlone</th>\n",
              "      <th>FareBand</th>\n",
              "      <th>AgeBand</th>\n",
              "      <th>Survived</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>-0.557365</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>-0.502445</td>\n",
              "      <td>2</td>\n",
              "      <td>2</td>\n",
              "      <td>0.059160</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>2.0</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0.649713</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0.786845</td>\n",
              "      <td>0</td>\n",
              "      <td>3</td>\n",
              "      <td>0.059160</td>\n",
              "      <td>0</td>\n",
              "      <td>3</td>\n",
              "      <td>3.0</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>3</td>\n",
              "      <td>0</td>\n",
              "      <td>-0.255596</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>-0.488854</td>\n",
              "      <td>2</td>\n",
              "      <td>1</td>\n",
              "      <td>-0.560975</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>2.0</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0.423386</td>\n",
              "      <td>1</td>\n",
              "      <td>0</td>\n",
              "      <td>0.420730</td>\n",
              "      <td>2</td>\n",
              "      <td>3</td>\n",
              "      <td>0.059160</td>\n",
              "      <td>0</td>\n",
              "      <td>3</td>\n",
              "      <td>2.0</td>\n",
              "      <td>1</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>3</td>\n",
              "      <td>1</td>\n",
              "      <td>0.423386</td>\n",
              "      <td>0</td>\n",
              "      <td>0</td>\n",
              "      <td>-0.486337</td>\n",
              "      <td>2</td>\n",
              "      <td>2</td>\n",
              "      <td>-0.560975</td>\n",
              "      <td>1</td>\n",
              "      <td>1</td>\n",
              "      <td>2.0</td>\n",
              "      <td>0</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-f0a77a0c-65d4-44d3-960f-693431d3187f')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-f0a77a0c-65d4-44d3-960f-693431d3187f button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-f0a77a0c-65d4-44d3-960f-693431d3187f');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "df_clean",
              "summary": "{\n  \"name\": \"df_clean\",\n  \"rows\": 891,\n  \"fields\": [\n    {\n      \"column\": \"Pclass\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 1,\n        \"max\": 3,\n        \"num_unique_values\": 3,\n        \"samples\": [\n          3,\n          1,\n          2\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Sex\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 1,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          0,\n          1\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Age\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1.0005616400330486,\n        \"min\": -2.185411864575735,\n        \"max\": 3.818293335410971,\n        \"num_unique_values\": 90,\n        \"samples\": [\n          0.27250112129467047,\n          2.76209990992952\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"SibSp\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1,\n        \"min\": 0,\n        \"max\": 8,\n        \"num_unique_values\": 7,\n        \"samples\": [\n          1,\n          0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Parch\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 6,\n        \"num_unique_values\": 7,\n        \"samples\": [\n          0,\n          1\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Fare\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1.0005616400330462,\n        \"min\": -0.6484216535389205,\n        \"max\": 9.667166525013505,\n        \"num_unique_values\": 248,\n        \"samples\": [\n          -0.42207354059350805,\n          0.395813560675251\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Embarked\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 2,\n        \"num_unique_values\": 3,\n        \"samples\": [\n          2,\n          0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Title\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 4,\n        \"num_unique_values\": 5,\n        \"samples\": [\n          3,\n          4\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"FamilySize\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1.000561640033051,\n        \"min\": -0.5609748304808925,\n        \"max\": 5.64037224096421,\n        \"num_unique_values\": 9,\n        \"samples\": [\n          3.779968119530679,\n          -0.5609748304808925\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"IsAlone\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 1,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          1,\n          0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"FareBand\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 1,\n        \"min\": 0,\n        \"max\": 3,\n        \"num_unique_values\": 4,\n        \"samples\": [\n          3,\n          2\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"AgeBand\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0.8515376279753577,\n        \"min\": 0.0,\n        \"max\": 4.0,\n        \"num_unique_values\": 5,\n        \"samples\": [\n          3.0,\n          4.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Survived\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 0,\n        \"min\": 0,\n        \"max\": 1,\n        \"num_unique_values\": 2,\n        \"samples\": [\n          1,\n          0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {},
          "execution_count": 12
        }
      ]
    }
  ]
}