# -*- coding: utf-8 -*-
"""Tarea08062026.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lu5OMb7o7A2b5aVzUz7lfCZcvui6Nez_

# Sistema Multi-Agente — Dataset Titanic

1. INSTALACIÓN DE DEPENDENCIAS
"""

!pip install -q \
    langchain \
    langchain-mistralai \
    langchain-experimental \
    transformers \
    torch \
    scikit-learn \
    pandas \
    numpy \
    matplotlib \
    seaborn \
    tabulate

"""2. Imports y configuración global"""

import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# LangChain
from langchain_mistralai import ChatMistralAI
from langchain_experimental.agents import create_pandas_dataframe_agent

# Scikit-learn
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score, roc_auc_score,
    classification_report, confusion_matrix
)

# Transformers
import torch


print("Imports OK")
print(f"PyTorch version: {torch.__version__}")
print(f"Dispositivo: {'cuda' if torch.cuda.is_available() else 'cpu'}")

"""3. Configuracion del LLM (Mistral)"""

MISTRAL_API_KEY = "1rOo1HhaMfhbuEhWiAusjvx2LOXlWKr9"

llm = ChatMistralAI(
    api_key=MISTRAL_API_KEY,
    model="mistral-small-latest",
    temperature=0
)

print("LLM configurado correctamente")

"""4. Carga del Dataset"""

from google.colab import files
uploaded = files.upload()
df_raw = pd.read_csv(list(uploaded.keys())[0])

"""5. AGENTE 1 — Normalizador"""

prefix_normalizador = """
Eres el Agente Normalizador dentro de un pipeline de Machine Learning.
Tu unica responsabilidad es analizar el DataFrame y describir con precision
que transformaciones son necesarias para dejarlo listo para el entrenamiento.

Debes identificar y reportar:
1. Columnas con valores nulos y la estrategia de imputacion adecuada.
2. Columnas categoricas que requieren codificacion.
3. Columnas numericas que requieren escalado.
4. Columnas irrelevantes o de alta cardinalidad que deben eliminarse.
5. Posibles features nuevas que se puedan derivar de las existentes.

Responde siempre en espanol. Se conciso y tecnico.
No ejecutes transformaciones, solo analiza y describe el plan.
"""

agente1 = create_pandas_dataframe_agent(
    llm,
    df_raw,
    prefix=prefix_normalizador,
    verbose=True,
    allow_dangerous_code=True,
    agent_type="tool-calling"
)

print("Agente 1 creado")

plan_normalizacion = agente1.invoke(
    "Analiza este dataset y describe el plan completo de normalizacion "
    "que se debe aplicar para prepararlo para un modelo de clasificacion."
)

print("\n" + "="*60)
print("PLAN DEL AGENTE 1:")
print("="*60)
print(plan_normalizacion['output'])

# Pipeline de normalizacion determinista basado en el plan del agente
print("="*60)
print("EJECUTANDO PIPELINE DE NORMALIZACION")
print("="*60)

df = df_raw.copy()
nombres = df['Name'].copy()   # guardamos nombres para DistilBERT en Agente 2

# 1. Eliminar columnas irrelevantes
df.drop(columns=['PassengerId', 'Ticket', 'Cabin'], inplace=True, errors='ignore')
print("[1] Columnas eliminadas: PassengerId, Ticket, Cabin")

# 2. Extraer titulo del nombre
df['Title'] = df['Name'].str.extract(r' ([A-Za-z]+)\.')
titulos_raros = df['Title'].value_counts()
df['Title'] = df['Title'].replace(titulos_raros[titulos_raros < 10].index, 'Rare')
print(f"[2] Titulos extraidos: {sorted(df['Title'].unique().tolist())}")

# 3. Imputacion
nulos_antes = df.isnull().sum().sum()
df['Age']      = df.groupby('Title')['Age'].transform(lambda x: x.fillna(x.median()))
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
df['Fare']     = df['Fare'].fillna(df['Fare'].median())
print(f"[3] Imputacion: {nulos_antes} nulos -> {df.isnull().sum().sum()}")

# 4. Feature engineering
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
df['IsAlone']    = (df['FamilySize'] == 1).astype(int)
df['FareBand']   = pd.qcut(df['Fare'], 4, labels=False, duplicates='drop')
df['AgeBand']    = pd.cut(df['Age'], bins=[0,12,18,35,60,100], labels=[0,1,2,3,4])
print("[4] Features creadas: FamilySize, IsAlone, FareBand, AgeBand")

# 5. Codificacion de categoricas
for col in ['Sex', 'Embarked', 'Title']:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))
print("[5] Codificacion LabelEncoder: Sex, Embarked, Title")

# 6. Escalado de numericas
scaler   = StandardScaler()
cols_esc = ['Age', 'Fare', 'FamilySize']
df[cols_esc] = scaler.fit_transform(df[cols_esc])
print(f"[6] Escalado StandardScaler: {cols_esc}")

# Dataset limpio final
feature_cols = ['Pclass','Sex','Age','SibSp','Parch','Fare',
                'Embarked','Title','FamilySize','IsAlone','FareBand','AgeBand']
df_clean = df[feature_cols + ['Survived']].copy()
df_clean['AgeBand'] = df_clean['AgeBand'].astype(float)

print(f"\nDataset limpio: {df_clean.shape[0]} filas x {df_clean.shape[1]} columnas")
df_clean.head()

"""AGENTE 2 — Entrenador

"""

prefix_entrenador = """
Eres el Agente Entrenador dentro de un pipeline de Machine Learning.
Recibes un DataFrame ya normalizado con features listas para entrenar.
La variable objetivo es 'Survived' (clasificacion binaria: 0 o 1).

Tu responsabilidad es:
1. Analizar las features disponibles y su relevancia para el problema.
2. Recomendar que modelos de clasificacion son mas adecuados y por que.
3. Describir la estrategia de validacion que usaras.
4. Identificar posibles problemas como desbalance de clases.

Nota importante: el pipeline ya incorpora embeddings de DistilBERT
(un modelo Transformer de HuggingFace) a partir de los nombres de los
pasajeros, que se concatenan con las features tabulares.

Responde siempre en espanol. Se conciso y tecnico.
"""

agente2 = create_pandas_dataframe_agent(
    llm,
    df_clean,
    prefix=prefix_entrenador,
    verbose=True,
    allow_dangerous_code=True,
    agent_type="tool-calling"
)

print("Agente 2 creado")

# El agente analiza el dataset limpio y describe la estrategia de entrenamiento
plan_entrenamiento = agente2.invoke(
    "Analiza el dataset limpio y describe la estrategia de entrenamiento: "
    "que modelos usarias, como validarias y que aspectos del dataset hay que considerar."
)

print("\n" + "="*60)
print("PLAN DEL AGENTE 2:")
print("="*60)
print(plan_entrenamiento['output'])

# --- Construccion de la feature matrix ---
feat_cols = [c for c in df_clean.columns if c != 'Survived']
X = df_clean[feat_cols].values
y = df_clean['Survived'].values
print(f"Feature matrix final: {X.shape}")

# Validacion cruzada estratificada
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

candidatos = {
    'Logistic Regression' : LogisticRegression(max_iter=1000, random_state=42),
    'Random Forest'       : RandomForestClassifier(n_estimators=200, random_state=42),
    'Gradient Boosting'   : GradientBoostingClassifier(n_estimators=200, random_state=42),
}

resultados = {}
print("\nValidacion cruzada (5 folds):")
print("-"*50)
for nombre, modelo in candidatos.items():
    scores = cross_val_score(modelo, X, y, cv=cv, scoring='accuracy')
    resultados[nombre] = {'mean': scores.mean(), 'std': scores.std(), 'scores': scores}
    print(f"  {nombre:25s} -> {scores.mean():.4f} +/- {scores.std():.4f}")

# Seleccionar el mejor modelo
nombre_modelo = max(resultados, key=lambda k: resultados[k]['mean'])
print(f"\nModelo ganador: {nombre_modelo}")

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

mejor_modelo = candidatos[nombre_modelo]
mejor_modelo.fit(X_train, y_train)

y_pred = mejor_modelo.predict(X_test)
y_prob = mejor_modelo.predict_proba(X_test)[:, 1]

metricas = {
    'accuracy'  : accuracy_score(y_test, y_pred),
    'roc_auc'   : roc_auc_score(y_test, y_prob),
    'report'    : classification_report(y_test, y_pred),
    'cm'        : confusion_matrix(y_test, y_pred),
    'cv_results': resultados
}

print(f"\nAccuracy final : {metricas['accuracy']:.4f}")
print(f"AUC-ROC final  : {metricas['roc_auc']:.4f}")

# --- Construccion de la feature matrix y entrenamiento ---
feat_cols = [c for c in df_clean.columns if c != 'Survived']
X = df_clean[feat_cols].values
y         = df_clean['Survived'].values
print(f"Feature matrix final: {X.shape}  (tabulares + embeddings DistilBERT)")

# Validacion cruzada estratificada
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

candidatos = {
    'Logistic Regression' : LogisticRegression(max_iter=1000, random_state=42),
    'Random Forest'       : RandomForestClassifier(n_estimators=200, random_state=42),
    'Gradient Boosting'   : GradientBoostingClassifier(n_estimators=200, random_state=42),
}

resultados = {}
print("\nValidacion cruzada (5 folds):")
print("-"*50)
for nombre, modelo in candidatos.items():
    scores = cross_val_score(modelo, X, y, cv=cv, scoring='accuracy')
    resultados[nombre] = {'mean': scores.mean(), 'std': scores.std(), 'scores': scores}
    print(f"  {nombre:25s} -> {scores.mean():.4f} +/- {scores.std():.4f}")

# Seleccionar el mejor modelo
nombre_modelo = max(resultados, key=lambda k: resultados[k]['mean'])
print(f"\nModelo ganador: {nombre_modelo}")

# Train/test split y reentrenamiento solo sobre train
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

mejor_modelo = candidatos[nombre_modelo]
mejor_modelo.fit(X_train, y_train)

# Metricas finales sobre test
y_pred = mejor_modelo.predict(X_test)
y_prob = mejor_modelo.predict_proba(X_test)[:, 1]

metricas = {
    'accuracy'  : accuracy_score(y_test, y_pred),
    'roc_auc'   : roc_auc_score(y_test, y_prob),
    'report'    : classification_report(y_test, y_pred),
    'cm'        : confusion_matrix(y_test, y_pred),
    'cv_results': resultados
}

print(f"Feature matrix final: {X.shape}")

from sklearn.metrics import RocCurveDisplay

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# --- Comparacion de modelos ---
modelos = list(resultados.keys())
medias  = [resultados[m]['mean'] for m in modelos]
stds    = [resultados[m]['std']  for m in modelos]
colores = ['#4C72B0' if m != nombre_modelo else '#DD8452' for m in modelos]

axes[0].barh(modelos, medias, xerr=stds, color=colores, edgecolor='white', height=0.5)
axes[0].set_xlim(0.7, 1.0)
axes[0].set_xlabel('Accuracy (CV 5-fold)')
axes[0].set_title('Comparacion de modelos')
for i, m in enumerate(medias):
    axes[0].text(m + 0.002, i, f'{m:.4f}', va='center', fontsize=10)

# --- Matriz de confusion ---
cm = metricas['cm']
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=axes[1],
            xticklabels=['No sobrevivio', 'Sobrevivio'],
            yticklabels=['No sobrevivio', 'Sobrevivio'])
axes[1].set_title(f'Matriz de confusion — {nombre_modelo}')
axes[1].set_xlabel('Prediccion')
axes[1].set_ylabel('Real')

# --- Curva ROC ---
RocCurveDisplay.from_predictions(
    y_test, y_prob,
    ax=axes[2],
    color='#DD8452',
    name=nombre_modelo
)
axes[2].plot([0, 1], [0, 1], 'k--', label='Azar')
axes[2].set_title('Curva ROC')
axes[2].legend()

plt.tight_layout()
plt.show()

print("\nReporte de clasificacion:")
print(metricas['report'])

"""AGENTE 3 — Comunicador

Celda 1 — Instalación:
"""

!pip install -q faiss-cpu langchain langchain-mistralai

"""Celda 2 — Imports y construcción del RAG:"""

import os
import json
from langchain_mistralai import ChatMistralAI, MistralAIEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import PromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
from langchain_core.documents import Document

print("Imports Agente 3 OK")

"""Celda 3 — Construir documentos y base vectorial:"""

from langchain_community.vectorstores import FAISS

# --- Construir documentos con datos del Titanic ---
print("="*60)
print("AGENTE 3 — COMUNICADOR RAG")
print("="*60)

# Documento con estadisticas globales del dataset
total         = len(df_raw)
sobrevivieron = int(df_raw['Survived'].sum())
murieron      = total - sobrevivieron
pct_surv      = round(sobrevivieron / total * 100, 2)
surv_sexo     = df_raw.groupby('Sex')['Survived'].mean().round(4).to_dict()
surv_clase    = df_raw.groupby('Pclass')['Survived'].mean().round(4).to_dict()
edad_media    = round(df_raw['Age'].mean(), 2)
nulos_age     = int(df_raw['Age'].isnull().sum())

doc_dataset = Document(
    page_content=f"""
ESTADISTICAS GLOBALES — DATASET TITANIC
Total de pasajeros: {total}
Sobrevivieron: {sobrevivieron} ({pct_surv}%)
Murieron: {murieron} ({round(100 - pct_surv, 2)}%)
Tasa de supervivencia por sexo: {surv_sexo}
Tasa de supervivencia por clase: {surv_clase}
Edad promedio: {edad_media} anos
Valores nulos en Age: {nulos_age}
Preprocesamiento (Agente 1):
- Columnas eliminadas: PassengerId, Ticket, Cabin
- Imputacion: Age por mediana segun titulo, Embarked por moda
- Features creadas: FamilySize, IsAlone, FareBand, AgeBand
- Codificacion: LabelEncoder en Sex, Embarked, Title
- Escalado: StandardScaler en Age, Fare, FamilySize
""",
    metadata={"fuente": "estadisticas_dataset"}
)

# Documento con metricas del modelo
cv_res = metricas['cv_results']
doc_metricas = Document(
    page_content=f"""
RESULTADOS DEL ENTRENAMIENTO — AGENTE 2
Modelo ganador: {nombre_modelo}
Accuracy final (test): {round(metricas['accuracy'], 4)}
AUC-ROC final (test): {round(metricas['roc_auc'], 4)}
Validacion cruzada (5 folds):
{chr(10).join([f"- {m}: {cv_res[m]['mean']:.4f} +/- {cv_res[m]['std']:.4f}" for m in cv_res])}
Reporte de clasificacion:
{metricas['report']}
""",
    metadata={"fuente": "metricas_modelo"}
)
# Documento con supervivencia detallada por clase y sexo
surv_clase_sexo = df_raw.groupby(['Pclass', 'Sex'])['Survived'].agg(['sum', 'count']).reset_index()
surv_por_clase  = df_raw[df_raw['Survived']==1]['Pclass'].value_counts().sort_index().to_dict()
muertes_clase   = df_raw[df_raw['Survived']==0]['Pclass'].value_counts().sort_index().to_dict()
surv_edad       = df_raw.groupby('Survived')['Age'].mean().round(2).to_dict()
ninos_surv      = int(df_raw[(df_raw['Age'] < 18) & (df_raw['Survived']==1)].shape[0])
ninos_total     = int(df_raw[df_raw['Age'] < 18].shape[0])

doc_detalle = Document(
    page_content=f"""
DETALLE DE SUPERVIVENCIA — DATASET TITANIC

Sobrevivientes por clase:
- Primera clase: {surv_por_clase.get(1, 0)} sobrevivientes
- Segunda clase: {surv_por_clase.get(2, 0)} sobrevivientes
- Tercera clase: {surv_por_clase.get(3, 0)} sobrevivientes

Fallecidos por clase:
- Primera clase: {muertes_clase.get(1, 0)} fallecidos
- Segunda clase: {muertes_clase.get(2, 0)} fallecidos
- Tercera clase: {muertes_clase.get(3, 0)} fallecidos

Edad promedio sobrevivientes: {surv_edad.get(1, 0)} anos
Edad promedio fallecidos: {surv_edad.get(0, 0)} anos

Ninos (menores de 18):
- Total: {ninos_total}
- Sobrevivieron: {ninos_surv}
- Fallecieron: {ninos_total - ninos_surv}
""",
    metadata={"fuente": "detalle_supervivencia"}
)

# Convertir cada fila del dataset en un documento
def fila_a_texto(row):
    return (
        f"Pasajero — Clase: {row['Pclass']}, Sexo: {row['Sex']}, "
        f"Edad: {row['Age']}, Sobrevivio: {'Si' if row['Survived'] == 1 else 'No'}, "
        f"Tarifa: {row['Fare']}, Embarco: {row['Embarked']}, "
        f"Familiares: {row['SibSp'] + row['Parch']}"
    )

docs_pasajeros = [
    Document(page_content=fila_a_texto(row), metadata={"fuente": "pasajero"})
    for _, row in df_raw.iterrows()
]

# Filtrar documentos vacios
todos_los_docs = [doc_dataset, doc_metricas, doc_detalle] + docs_pasajeros
todos_los_docs = [d for d in todos_los_docs if len(d.page_content.strip()) > 10]
print(f"Documentos validos: {len(todos_los_docs)}")

# --- Embeddings con Mistral y base vectorial FAISS ---
print("\nGenerando embeddings con Mistral... (puede tardar 2-3 minutos)")

embeddings = MistralAIEmbeddings(
    api_key=MISTRAL_API_KEY,
    model="mistral-embed"
)

# Procesar en lotes para evitar errores de API
batch_size  = 50
vectorstore = None

for i in range(0, len(todos_los_docs), batch_size):
    batch = todos_los_docs[i : i + batch_size]
    print(f"Procesando lote {i//batch_size + 1}/{-(-len(todos_los_docs)//batch_size)}...")
    if vectorstore is None:
        vectorstore = FAISS.from_documents(batch, embeddings)
    else:
        vectorstore.add_documents(batch)

retriever = vectorstore.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 6}
)

print("Base vectorial FAISS lista")

"""Celda 4 — Cadena RAG y loop interactivo:


"""

# --- Cadena RAG ---
PROMPT_TEMPLATE = """
Sos un analista experto en datos del Titanic y machine learning.
Responde en castellano usando UNICAMENTE la informacion del contexto.
Si la informacion no esta en el contexto, decí:
"No tengo suficientes datos para responder eso."

Contexto:
{context}

Pregunta: {question}

Respuesta:
"""

prompt = PromptTemplate(
    input_variables=["context", "question"],
    template=PROMPT_TEMPLATE
)

def formatear_docs(docs):
    contexto_fijo = doc_dataset.page_content + "\n\n---\n" + doc_metricas.page_content + "\n\n---\n" + doc_detalle.page_content
    contexto_recuperado = "\n\n---\n".join(doc.page_content for doc in docs)
    return contexto_fijo + "\n\n---\n" + contexto_recuperado

cadena_rag = (
    {
        "context" : retriever | formatear_docs,
        "question": RunnablePassthrough()
    }
    | prompt
    | llm
    | StrOutputParser()
)

print("Agente 3 listo.")
print("Ejemplos de preguntas:")
print("  - Cuantos pasajeros sobrevivieron?")
print("  - Cual fue el modelo con mejor accuracy?")
print("  - Cual es la tasa de supervivencia por sexo?")
print("  - Cuantos valores nulos habia en Age?")
print("-"*50)

while True:
    pregunta = input("Tu pregunta: ").strip()

    if pregunta.lower() in ['salir', 'exit', 'quit', 'q']:
        print("Agente 3 finalizado.")
        break

    if not pregunta:
        continue

    respuesta = cadena_rag.invoke(pregunta)
    print(f"\nRespuesta: {respuesta}\n")